#!/usr/bin/env bash
# Pull the SpoolmanSync-generated Home Assistant config into the repo.
#
# SpoolmanSync's own auto-configure writes two files: packages/spoolmansync.yaml
# (the rest_command / input_number / utility_meter / sensor block) and HA's
# automations.yaml (the deduction automations). That second file is UI-managed
# and not tracked here, so this script folds both halves into the single
# git-managed package file instead — HA packages accept `automation:` as a
# top-level key, so the combined file is equivalent and stays in git.
#
# Requires SpoolmanSync to already be connected to Home Assistant (an OAuth
# browser flow — see docs/superpowers/plans/2026-08-06-spool-management.md).
#
# Usage: stacks/spoolman/scripts/sync-ha-package.sh
set -euo pipefail

SPOOLMANSYNC_URL="${SPOOLMANSYNC_URL:-https://spools.tylercash.dev}"
# The URL Home Assistant posts usage back to. HA and SpoolmanSync share the
# homelab_default network, so the container name avoids a round trip through
# Traefik and its ClientIP guard.
WEBHOOK_URL="${WEBHOOK_URL:-http://spoolmansync:3000}"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
out="$repo_root/stacks/home-assistant/packages/spoolmansync.yaml"

command -v jq >/dev/null || { echo "❌ jq not found" >&2; exit 1; }

echo "→ Checking SpoolmanSync connection state..."
state=$(curl -sf "$SPOOLMANSYNC_URL/api/automations") || {
    echo "❌ Cannot reach $SPOOLMANSYNC_URL" >&2; exit 1
}
if [ "$(jq -r '.haConnected' <<<"$state")" != "true" ]; then
    echo "❌ SpoolmanSync is not connected to Home Assistant yet." >&2
    echo "   Connect it at $SPOOLMANSYNC_URL → Settings (OAuth browser flow)," >&2
    echo "   then re-run this script." >&2
    exit 1
fi

echo "→ Discovering printers and generating config..."
resp=$(curl -sf -X POST "$SPOOLMANSYNC_URL/api/automations" \
    -H 'Content-Type: application/json' \
    -d "$(jq -nc --arg w "$WEBHOOK_URL" '{action:"discover", webhookUrl:$w}')") || {
    echo "❌ discover failed. SpoolmanSync returned an error — check that ha-bambulab" >&2
    echo "   is configured and at least one printer is visible in SpoolmanSync." >&2
    exit 1
}

if [ "$(jq -r 'has("error")' <<<"$resp")" = "true" ]; then
    echo "❌ $(jq -r '.error' <<<"$resp")" >&2; exit 1
fi

printers=$(jq -r '.printerCount' <<<"$resp")
trays=$(jq -r '.trayCount' <<<"$resp")
echo "   discovered $printers printer(s), $trays tray(s)"

# A missing print_weight entity means usage silently never gets deducted, which
# is the failure mode this whole setup exists to avoid. Surface it loudly.
if [ "$(jq -r '.missingEntities | length' <<<"$resp")" != "0" ]; then
    echo "⚠️  Home Assistant entities are missing:" >&2
    jq -r '.missingEntities[] | "     \(.name // .prefix): \(.missing | join(", "))"' <<<"$resp" >&2
    if jq -e '[.missingEntities[] | select(.breaksUsageTracking)] | length > 0' <<<"$resp" >/dev/null; then
        echo "   ⛔ At least one breaks usage tracking — weight will never be deducted." >&2
        echo "      Fix the integration before relying on this." >&2
    fi
fi

mkdir -p "$(dirname "$out")"
{
    echo "# SpoolmanSync package — generated by stacks/spoolman/scripts/sync-ha-package.sh"
    echo "# Do not edit by hand: re-run the script instead, or the next sync drops your changes."
    echo "#"
    echo "# Combines SpoolmanSync's configuration additions (rest_command, input_number,"
    echo "# utility_meter, sensor) with its automations, which upstream would otherwise"
    echo "# split across configuration.yaml and the UI-managed automations.yaml."
    echo
    # Strip the generator's own leading comment/banner lines, matching upstream's
    # toPackageFileContent (ha-config-generator.ts:1415).
    jq -r '.configurationYaml' <<<"$resp" | sed -e '/^[[:space:]]*[#=]/d' -e '/./,$!d'
    echo
    echo "automation:"
    # A YAML list may sit at the same indentation as its parent key, so the
    # generated block nests without re-indenting (and without risking a mangle
    # of its multi-line Jinja templates).
    jq -r '.automationsYaml' <<<"$resp"
} > "$out"

echo "✅ Wrote $out"
echo
echo "Next:"
echo "  git add stacks/home-assistant/packages/spoolmansync.yaml"
echo "  git commit -m 'feat(home-assistant): add spoolmansync usage-tracking package'"
echo "  git push   # STACK_CONTENT_HASH recreates HA and loads the package"
