version: '3'

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "3"
      labels: "com.docker.compose.service,com.docker.compose.project"

services:
  github-runner:
    <<: *logging
    container_name: github-runner
    build: .
    restart: unless-stopped
    environment:
      - RUNNER_SCOPE=repo
      - REPO_URL=${REPO_URL}
      - ACCESS_TOKEN=${GITHUB_PAT}
      - RUNNER_NAME=homelab
      - RUNNER_WORKDIR=/tmp/runner/work
      - LABELS=self-hosted,linux
      - SOPS_AGE_KEY=${SOPS_AGE_KEY}
    networks:
      - homelab_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  homelab_default:
    external: true
